### PR TITLE
confusion on pluto

### PR DESCRIPTION
**Pull request by ashutoshvt**
Added a question about pluto.

### CODE REVIEW

**Comment by loriab** [comment]
Can you elaborate with a reference about this confusion? I happen to know Pluto _is_ a planet.

**Comment by ashutoshvt** [comment]
http://news.nationalgeographic.com/news/2006/08/060824-pluto-planet.html

**Comment by loriab** [comment]
Very well. Please add this reference to the repo.

**Comment by dsirianni** [comment]
Aparrently I was beaten to the punch. I'll pull in his changes to my branch.

**Pull request merged**
