### PR TITLE
Venus data

### PR DESCRIPTION
**Pull request by mlestep**
Adds the length of the rotational period of Venus about the Sun.

### CODE REVIEW

**Comment by loriab** [comment]
Aha, you shouldn't have LICENSE commits here. Try `git pull --rebase upstream master`

**Comment by mlestep** [comment]
Ah, thank you! I've run the command you've requested, and hope there are no conflicts left.

**Review by amjames — CHANGES_REQUESTED** [review]
It looks like you have modified the license!

**Comment by dgasmith** [comment]
@quantumbutterfly Once you run that command you need to push this back to your branch. You can do this by `git push origin venus-orbit`. You may be bounced on this in which you need to do `git push --force origin venus-orbit` so that you overwrite the remote's history with your laptop's.

**Pull request closed without merging**
