### PR TITLE
added Europa

### PR DESCRIPTION
**Pull request by schiebermc**
Added a file for Europa.

### CODE REVIEW

**Comment by loriab** [comment]
Want to move this to a jupiter_moons directory?

**Comment by schiebermc** [comment]
Okay, I added the info directly to the Jupiter file and also deleted the Europa file.

**Comment by loriab** [comment]
I meant to suggest that you make a directory jupiter_moons, then add Europa to that dir.

**Comment by schiebermc** [comment]
Ahhh, got ya. I added a Jupiter_moons file and put the info there.

**Comment by loriab** [comment]
Not quite, I was hoping for a directory. But ok.

**Pull request merged**
